### ISSUE TITLE
Create Validation request Middlewares

### ISSUE THREAD

**Issue by wmezadev** [wmezadev/CSE341-TEAM2#7]
The idea is to use validator.js and catch request body before sending data to the actual controller
We are going to work with two entities (collections or tables if you want to call it): Boardgame and Reviews.

You can take a look to my previous project to see how I use request middleware to validate data: [@wmezadev cse-341-project](https://github.com/wmezadev/cse-341-project/tree/main/requests)

Work closely with @sbunkerchris to understand data schema. You can take our swagger doc for reference too.
[boardgame swagger](https://boardgame-team2.onrender.com/api-docs/#/)

**Comment by ojorojustice** [comment]
Seen. Thanks.
